# Generated by Django 5.0.4 on 2024-05-11 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_id', models.CharField(max_length=200)),
                ('ac', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=200)),
                ('de', models.TextField()),
                ('kw', models.TextField()),
                ('os', models.TextField()),
                ('ra', models.TextField()),
                ('rt', models.TextField()),
                ('rl', models.TextField()),
                ('rc', models.TextField()),
                ('rd', models.TextField()),
                ('sq', models.CharField(max_length=200)),
            ],
        ),
    ]
