# Generated by Django 5.0.4 on 2024-04-08 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_id', models.CharField(max_length=200)),
                ('ac', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=200)),
                ('de', models.CharField(max_length=200)),
                ('kw', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('ra', models.CharField(max_length=200)),
                ('rt', models.CharField(max_length=200)),
                ('rl', models.CharField(max_length=200)),
                ('rd', models.CharField(max_length=200)),
                ('sq', models.CharField(max_length=200)),
            ],
        ),
    ]
