# Generated by Django 5.0.4 on 2024-05-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_factor_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='factor_id',
        ),
        migrations.AlterField(
            model_name='factor',
            name='ac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='dt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='kw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='ra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='rc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='rl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='rt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='sq',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
