# Generated by Django 5.0.4 on 2024-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_remove_factor_factor_id_alter_factor_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='factor_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
