# Generated by Django 5.0.4 on 2024-05-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0004_factor_factor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='factor_id',
        ),
    ]
