# Generated by Django 5.0.6 on 2024-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0005_remove_factor_factor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
