# Generated by Django 5.0.4 on 2024-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0006_factor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
