# Generated by Django 5.0.4 on 2024-06-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0007_alter_factor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
