# Generated by Django 5.0.6 on 2024-07-09 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0008_alter_factor_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionLabels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_label', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='ft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factors.functionlabels'),
        ),
    ]
