# Generated by Django 5.0.4 on 2024-05-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0005_remove_factor_factor_id'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Belong_factor',
            field=models.ManyToManyField(blank=True, related_name='belong_factor', to='factors.factor'),
        ),
    ]
