# Generated by Django 5.0.4 on 2024-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0006_factor_color'),
        ('searchforcares', '0002_history_search_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_search_care',
            name='Ms',
        ),
        migrations.RemoveField(
            model_name='history_search_care',
            name='Ms_r',
        ),
        migrations.AddField(
            model_name='history_search_care',
            name='Ms',
            field=models.ManyToManyField(blank=True, related_name='Ms_factor', to='factors.factor'),
        ),
        migrations.AddField(
            model_name='history_search_care',
            name='Ms_r',
            field=models.ManyToManyField(blank=True, related_name='Ms_r_factor', to='factors.factor'),
        ),
    ]
