# Generated by Django 5.0.6 on 2024-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchforcares', '0003_remove_history_search_care_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_search_care',
            name='F_r',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='history_search_care',
            name='R_f_r',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
