# Generated by Django 5.0.4 on 2024-05-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biologist', '0002_alter_biologist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologist',
            name='user',
        ),
    ]
